import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/navbar";
import { IdleTimer } from "./idLeTimer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "InovaSoft | %s",
    default: "InovaSoft",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex h-full flex-col md:overflow-hidden">
          <IdleTimer />
          {/* <div
            className="fixed bottom-4 right-4 flex items-center gap-2 rounded-full px-4 py-2 text-xs font-mono text-white backdrop-blur-md border border-zinc-800 bg-zinc-900/80"
          >
          </div> */}
            {children}
        </div>
      </body>
    </html>
  );
}
